# Generated by Django 3.2.6 on 2021-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='charge_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='payment_intent_id',
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
