# Generated by Django 3.2.6 on 2021-10-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20211002_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripepayment',
            name='charge_id',
        ),
    ]
